language: python

sudo: false

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-dj22-drf311

    - python: 3.8
      env: TOXENV=py38-dj30-drf311

    - python: 3.8
      env: TOXENV=flake8

    - python: 3.8
      env: TOXENV=py38-doctest

install:
  - pip install tox

script:
    tox
