language: python

sudo: false

env:
    - TOX_ENV=py27-dj14
    - TOX_ENV=py27-dj15
    - TOX_ENV=py27-dj16
    - TOX_ENV=py27-dj17
    - TOX_ENV=py27-dj18
    - TOX_ENV=py34-dj15
    - TOX_ENV=py34-dj16
    - TOX_ENV=py34-dj17
    - TOX_ENV=py34-dj18
    - TOX_ENV=py27-dj14-drf24
    - TOX_ENV=py27-dj14-drf31
    - TOX_ENV=py27-dj15-drf24
    - TOX_ENV=py27-dj15-drf31
    - TOX_ENV=py27-dj16-drf24
    - TOX_ENV=py27-dj16-drf31
    - TOX_ENV=py27-dj17-drf24
    - TOX_ENV=py27-dj17-drf31
    - TOX_ENV=py27-dj18-drf24
    - TOX_ENV=py27-dj18-drf31
    - TOX_ENV=py34-dj15-drf24
    - TOX_ENV=py34-dj15-drf31
    - TOX_ENV=py34-dj16-drf24
    - TOX_ENV=py34-dj16-drf31
    - TOX_ENV=py34-dj17-drf24
    - TOX_ENV=py34-dj17-drf31
    - TOX_ENV=py34-dj18-drf24
    - TOX_ENV=py34-dj18-drf31
    - TOX_ENV=flake8
    - TOX_ENV=py34-doctest

install:
  - pip install tox

script:
    tox -e $TOX_ENV


