# -*- coding: utf-8 -*-
#
# Filternaut documentation build configuration file, created by
# sphinx-quickstart on Sat Feb 21 14:25:31 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

import django
from django.conf import settings

# hax -- lazy translation-proxies make doctests hard, so monkey patch them into
# no-ops.
from django.utils import translation

translation.ugettext_lazy = lambda s: s

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath("../"))

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.doctest",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
]

# The suffix of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Filternaut"
copyright = "2024, Ben Graham"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "1.0.0"
# The full version, including alpha/beta/rc tags.
release = "1.0.0"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", ".tox"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "github-dark"

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
try:
    import sphinx_press_theme

    html_theme = "press"
except ImportError:
    html_theme = "default"


try:
    settings.configure(
        DATABASES={
            "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}
        },
        INSTALLED_APPS=("django.contrib.auth", "django.contrib.contenttypes"),
    )
    django.setup()
except RuntimeError:
    pass

doctest_global_setup = """
from django.contrib.auth.models import User
import pprint
import filternaut
"""
